apiVersion: v1
kind: Secret
metadata:
  namespace: argocd
  name: staging-digitalocean-ams3-1
  labels:
    argocd.argoproj.io/secret-type: cluster
    environment: "staging"
    provider: "digitalocean"
type: Opaque
stringData:
  name: staging-digitalocean-ams3-1
  server: https://49bdff2d-4e89-476b-90de-01cebfbd687c.k8s.ondigitalocean.com
  config: |
    {
      "bearerToken": "dop_v1_2e88779a60e7af72efd721ce96271c68903847abadb270ef4e481969b2ead713", # dont push secrets into git NOTE:  use sealed secrets as a solution for secrets in gitops.
      "tlsClientConfig": {
        "insecure": false,
        "caData": "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlOVEExTVRReApPREkyTWpoYUZ3MDBOVEExTVRReE9ESTJNamhhTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFDb2o2ZC82cG5iNkdLRlBjTXlVbjVtMmxvbno5Z0Q3aEFZVkIrMTFlWm5USVhFVHlpUApNZGZjYU1IQjVVTmRWY2tWSGpyTisvK3VCVDdaOWRZOGZlWjFNaFVhbTRPdEx6V0czYlVNTmZmOFQzOVcyNUVtCmQ3cWZZT3ZtbjRPWU45SDR5eW1DUDdQemZCV1I4NjRsMWVocUwwY3lEb3VtVmgxSldySy80Nll5MmlQQjd2ZzkKYVhzczJYK0hXS1Q3TjJZYktqSXUvSnJpS3VNSU5KblVZbkJaaW01Z0c3cjFrL2tOY0UrVjdDOEIrLzVmeEViUQp5U3duR2Q1ZjF3SUpoVnV0SkZWZytiazFubnJQaFJKcXpETFBMcVp2UExHak5WV1hIODhRM255K3JsZEpiSW9jCnJvNG1uWityYjUrdTVnS1dUdk9VblBoemFBK1JVbXRkb1hpRkFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlRIL0dxOW9vSDI4VC9NQTFjaAo3S2FaZ29pL0lqQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFQUmR0NDNtOVRoMjd6TnlmZHlJTmdxU29nazh2CitQNEIzdEZkSDRJSmJmbC9XUWliQ3k4TFlhOTZzRVpmbzRMbEhhTisxbGd2MTdZNmUyTnlNcjh3K3VFc3cxRmEKekhxdmdzME1oZURWRzQzZ0ErbUZ6YVlBQmprOFM3SlVvVlVJMytXNlJ1b3dWYkY3ZXlKUG0xYTZtVVBteHlscQpBV0RiQkNqdmowcW9PcWpCV21iTVVsbi9wcWFObEZWMEtiZSs3MUMvQTJ0a2RxQnBLUVgxWkErRnhCYjFtU0FzCnYzdUJONHhkYXBJcGVYWFFQc0d5YkVIVEt6RFFwMVpESDlNbDZFYXR1cTBrOGFBdzRBRElOQVVqSGkvUE1USGkKdDYrUUZFcjAyR01uMXg4UlplQVE1dnlUU1BLUjZmZE9tdXVrOHA3S0kxZ2lyM0FCbHJteGFETXdoQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
      }
    }
