apiVersion: v1
kind: Secret
metadata:
  namespace: argocd
  name: staging-digitalocean-ams3-1
  labels:
    argocd.argoproj.io/secret-type: cluster
    environment: "staging"
    provider: "digitalocean"
type: Opaque
stringData:
  name: staging-digitalocean-ams3-1
  server: https://84387a76-1b43-4303-b74b-5ad49ca7785e.k8s.ondigitalocean.com
  config: |
    {
      "bearerToken": "dop_v1_00e17d9035aec333754082dd4644589458b99a8236c16c30513fa19e802003c3",
      "tlsClientConfig": {
        "insecure": false,
        "caData": "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlOVEExTVRVeApOVEl5TkRCYUZ3MDBOVEExTVRVeE5USXlOREJhTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFDN1JzM051NEFicmk1UnA1NVFwQW00dG1WTDNoaEFtbzhqM3JvRmNFcm9wOEpJY3U1cgpuTHkvS0dBNTFrSjBPNW14a0E1b0FoM1BwdEpYY0taUDBWK0hYeGxVd3RrczdsY2FvdWtIRi8vbzc1QlVibFhlClRzOWdVZ1ErZUY1WXFUTlltNEhlMEJETktSTjZVRUVNZHpSWk9XUkR2Q05SUjRJamthSURqc1BiV2xhdHJPK3gKc2R5K2NtTUNUTHkwWE41RDgwUkJPeUcyQ2pEeVFWVVBTaTRNeUVYL3d2eTNBVk9Jdm9XU2p1R2lPR3lHTjVFRQpYQjNnQmtjUDFPSkNPR1RwQVZ4UXk5OThhZDV5MnlyeExJMUtBNmtKMHVrNEVUMnB3Zm5oQVZHZkdjaW1rSGxjClR2TXlxdU03RStvOVArU1dtTkdlZnNpOFZDK1BGelE2aXhqVEFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlN1RkhOcmsrMXF2c2VFcmhLZwo5TG9EcHEydmFqQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFoSm9JMEZ5dkl0QmxiUG9tNFFVbmVIYktxQmFnCnVlbzRwMW5ubGtlOEhRU2VWWG5EZlZ3cVZLRHF5MUdEUmJVaDU5TkRVSDdROCtueDI3NUhBSlpiVStyMEU0eHkKMkFZazhKRHRBZGtwVWx4UzZDNDQzb1l3RHlyS1ZiUUIycGV6aG9reEZPUUduczQyMklaUGN3b3FaR25MS1VBVQpmV2ZibzVveHB0RHZtWXhQZ2UzUGQ2bWFlS2ZFZnducVIwaVMremtNQnJvMVNNNlBnODBsOUZXTFNKaXdmMEh4CjBObkIyOVNzbzFlVkpKWVVIWG9rcmc4NHR3OE5pVi8xdkdCQW1vbkdzTHphZ2EwWjg4MVFzdjVPeVAzdFI3bmkKRjFJc3BSd3hiR2YzVzZOZndMZ2Q5UTE2OUtBTWFTOHhXb0pwQmFNdTZVVFlLMVMwRTZsRTNyZys0dz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
      }
    }
