apiVersion: v1
kind: Secret
metadata:
  name: private-repo-https
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/feofilaktos/argocd-example-apps.git
  password: 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
  username: my-token
